apiVersion: v1
kind: Service
metadata:
  name: basic-service
spec:
  selector:
    app: basic
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
      nodePort: 30000  # must be between 30000-32767